-- TODAY_GYM 테이블 삭제--

-- MEMBER_TB 삭제
DROP TABLE MEMBER_TB CASCADE CONSTRAINTS;
DROP SYNONYM M;

-- BUY_TB 삭제
DROP TABLE BUY_TB CASCADE CONSTRAINTS;
DROP SYNONYM B;

-- CART_TB 삭제
DROP TABLE CART_TB CASCADE CONSTRAINTS;
DROP SYNONYM C;

-- PAY_TB 삭제
DROP TABLE PAY_TB CASCADE CONSTRAINTS;
DROP SYNONYM P;
DROP SEQUENCE PAY_SEQ;

-- BANK_TB 삭제
DROP TABLE BANK_TB CASCADE CONSTRAINTS;
DROP SYNONYM BK;

-- TICKET_TB 삭제
DROP TABLE TICKET_TB CASCADE CONSTRAINTS;
DROP SYNONYM T;
DROP SEQUENCE TICKET_SEQ;

-- REVIEW_TB 삭제
DROP TABLE REVIEW_TB CASCADE CONSTRAINTS;
DROP SYNONYM R;
DROP SEQUENCE REVIEW_SEQ;

-- RIMG_TB 삭제
DROP TABLE RIMG_TB CASCADE CONSTRAINTS;
DROP SYNONYM RI;
DROP SEQUENCE RIMG_SEQ;

-- SPOT_TB 삭제
DROP TABLE SPOT_TB CASCADE CONSTRAINTS;
DROP SYNONYM S;

-- SIMG_TB 삭제
DROP TABLE SIMG_TB CASCADE CONSTRAINTS;
DROP SYNONYM SI;
DROP SEQUENCE SIMG_SEQ;

-------------------------------------------------- MEMBER _TB
-- 테이블 생성
CREATE TABLE MEMBER_TB (
    M_ID	NVARCHAR2(20) NOT NULL,
    M_PW	NVARCHAR2(100) NOT NULL,
    M_NAME	NVARCHAR2(10) NOT NULL,
    M_EMAIL	NVARCHAR2(50) NOT NULL,
    M_PHONE	NVARCHAR2(11) NOT NULL,
    M_BIRTH	NVARCHAR2(6) NOT NULL,
    M_JOINDATE DATE DEFAULT SYSDATE NOT NULL,
    M_POINT	NUMBER DEFAULT 0 NOT NULL
    
    );

-- 동의어 생성
CREATE SYNONYM M FOR MEMBER_TB;

-- 기본키 생성
ALTER TABLE MEMBER_TB
ADD CONSTRAINT PK_M_ID PRIMARY KEY (M_ID);

-------------------------------------------------- BUY_TB
-- 테이블 생성
CREATE TABLE BUY_TB (
    B_CODE NVARCHAR2(20) NOT NULL,
    B_CATE NVARCHAR2(10) NOT NULL,
    B_SUBCATE NVARCHAR2(10) NOT NULL,
    B_TITLE NVARCHAR2(50) NOT NULL,
    B_TERM NVARCHAR2(10) NOT NULL,
    B_PRICE NUMBER NOT NULL
    
    );

-- 동의어 생성
CREATE SYNONYM B FOR BUY_TB;

-- 기본키 생성
ALTER TABLE BUY_TB
ADD CONSTRAINT PK_B_CODE PRIMARY KEY (B_CODE);

-------------------------------------------------- CART_TB
-- 테이블 생성
CREATE TABLE CART_TB (
    C_CODE NVARCHAR2(20) NOT NULL,
    M_ID NVARCHAR2(20) NOT NULL,
    B_CODE NVARCHAR2(20) NOT NULL
    
    );

-- 동의어 생성
CREATE SYNONYM C FOR CART_TB;

-- 기본키 생성
ALTER TABLE CART_TB
ADD CONSTRAINT PK_C_CODE PRIMARY KEY (C_CODE);

-- 외래키 생성 (회원정보)
ALTER TABLE CART_TB
ADD CONSTRAINT FK_M_ID FOREIGN KEY(M_ID)
REFERENCES MEMBER_TB(M_ID);

-- 외래키 생성 (상품정보)
ALTER TABLE CART_TB
ADD CONSTRAINT FK_B_CODE FOREIGN KEY(B_CODE)
REFERENCES BUY_TB(B_CODE);

-------------------------------------------------- PAY_TB
-- 테이블 생성
CREATE TABLE PAY_TB (
    P_NO NUMBER NOT NULL,
    C_CODE NVARCHAR2(20) NOT NULL,
    P_TOTAL NUMBER NOT NULL,
    P_DATE DATE DEFAULT SYSDATE,
    P_PAYMENT NVARCHAR2(20)
    
    );

-- 동의어 생성
CREATE SYNONYM P FOR PAY_TB;

-- 기본키 생성
ALTER TABLE PAY_TB
ADD CONSTRAINT PK_P_NO PRIMARY KEY (P_NO);

-- 외래키 생성
ALTER TABLE PAY_TB
ADD CONSTRAINT FK_C_CODE FOREIGN KEY(C_CODE)
REFERENCES CART_TB(C_CODE);

-- 결제번호 시퀀스
CREATE SEQUENCE PAY_SEQ
INCREMENT BY 1
START WITH 1 MINVALUE 1 MAXVALUE 1000 NOCYCLE;

-------------------------------------------------- BANK_TB
-- 테이블 생성
CREATE TABLE BANK_TB (
    BK_NO NUMBER NOT NULL,
    BK_ACCOUNT NVARCHAR2(20) NOT NULL,
    BK_PWD NVARCHAR2(20) NOT NULL,
    BK_NAME NVARCHAR2(20) NOT NULL,
    BK_CHECK NUMBER
    
    );

-- 동의어 생성
CREATE SYNONYM BK FOR BANK_TB;

-- 기본키 생성
ALTER TABLE BANK_TB
ADD CONSTRAINT PK_BK_NO PRIMARY KEY(BK_NO);

-------------------------------------------------- TICKET_TB
-- 테이블 생성
CREATE TABLE TICKET_TB (
    T_NO NUMBER NOT NULL,
    P_NO NUMBER NOT NULL,
    T_USE NCHAR(1) NOT NULL
    
    );
    
-- 동의어 생성
CREATE SYNONYM T FOR TICKET_TB;

-- 기본키 생성
ALTER TABLE TICKET_TB
ADD CONSTRAINT PK_T_NO PRIMARY KEY(T_NO);

-- 외래키 생성
ALTER TABLE TICKET_TB
ADD CONSTRAINT FK_P_NO FOREIGN KEY(P_NO)
REFERENCES PAY_TB(P_NO);

-- 발권 시퀀스
CREATE SEQUENCE TICKET_SEQ
INCREMENT BY 1
START WITH 1 MINVALUE 1 MAXVALUE 1000 NOCYCLE;

-------------------------------------------------- REVIEW_TB
-- 테이블 생성
CREATE TABLE REVIEW_TB (
    R_NO NUMBER NOT NULL, 
    R_CATE  NVARCHAR2(10) NOT NULL,
    R_TITLE NVARCHAR2(20) NOT NULL,
    R_CONTENTS NCLOB NOT NULL,
    M_ID NVARCHAR2(20) NOT NULL,
    R_DATE DATE NOT NULL,
    R_SCORE NUMBER NOT NULL
    
    );
    
-- 동의어 생성
CREATE SYNONYM R FOR REVIEW_TB;

-- 기본키 생성
ALTER TABLE REVIEW_TB
ADD CONSTRAINT PK_R_NO PRIMARY KEY(R_NO);

-- 외래키 생성
ALTER TABLE REVIEW_TB
ADD CONSTRAINT FK_R_M_ID FOREIGN KEY(M_ID)
REFERENCES MEMBER_TB(M_ID);

-- 리뷰 시퀀스
CREATE SEQUENCE REVIEW_SEQ
INCREMENT BY 1
START WITH 1 MINVALUE 1 MAXVALUE 1000 NOCYCLE;

-------------------------------------------------- RIMG_TB
-- 테이블 생성
CREATE TABLE RIMG_TB (
    RIMG_NO NUMBER NOT NULL,
    R_NO NUMBER NOT NULL,
    RIMG_ORI NVARCHAR2(500) NOT NULL,
    RIMG_SYS NVARCHAR2(50) NOT NULL
    
    );

-- 동의어 생성
CREATE SYNONYM RI FOR RIMG_TB;

-- 기본키 생성
ALTER TABLE RIMG_TB
ADD CONSTRAINT PK_RIMG_NO PRIMARY KEY(RIMG_NO);

-- 외래키 생성
ALTER TABLE RIMG_TB
ADD CONSTRAINT FK_R_NO FOREIGN KEY(R_NO)
REFERENCES REVIEW_TB(R_NO);

-- 리뷰 이미지 시퀀스
CREATE SEQUENCE RIMG_SEQ
INCREMENT BY 1
START WITH 1 MINVALUE 1 MAXVALUE 1000 NOCYCLE;

-------------------------------------------------- SPOT_TB
-- 테이블 생성
CREATE TABLE SPOT_TB (
    S_CODE NVARCHAR2(20) NOT NULL,
    S_NAME NVARCHAR2(20) NOT NULL,
    S_PHONE NVARCHAR2(11) NOT NULL,
    S_ADDR NVARCHAR2(50) NOT NULL,
    S_CONTENTS NCLOB
    
);

-- 동의어 생성
CREATE SYNONYM S FOR SPOT_TB;

-- 기본키 생성
ALTER TABLE SPOT_TB
ADD CONSTRAINT PK_S_CODE PRIMARY KEY(S_CODE);

-------------------------------------------------- SIMG_TB
-- 테이블 생성
CREATE TABLE SIMG_TB(
    SIMG_NO NUMBER NOT NULL,
    S_CODE NVARCHAR2(20) NOT NULL,
    SIMG_ORI NVARCHAR2(500) NOT NULL,
    SIMG_SYS NVARCHAR2(50) NOT NULL
    
    );

-- 동의어 생성
CREATE SYNONYM SI FOR SIMG_TB;

-- 기본키 생성
ALTER TABLE SIMG_TB
ADD CONSTRAINT PK_SIMG_NO PRIMARY KEY(SIMG_NO);

-- 외래키 생성
ALTER TABLE SIMG_TB
ADD CONSTRAINT FK_S_CODE FOREIGN KEY(S_CODE)
REFERENCES SPOT_TB(S_CODE);

-- 지점 이미지 시퀀스
CREATE SEQUENCE SIMG_SEQ
INCREMENT BY 1
START WITH 1 MINVALUE 1 MAXVALUE 1000 NOCYCLE;
    




